// This model represents a single flashcard in a deck
class Flashcard {
  final int? id;           // auto-generated by the DB
  final int deckId;        // foreign key linking to a deck
  final String question;
  final String answer;

  Flashcard({
    this.id,
    required this.deckId,
    required this.question,
    required this.answer,
  });

  // Convert DB map to flashcard object
  factory Flashcard.fromMap(Map<String, dynamic> map) {
    return Flashcard(
      id: map['id'],
      deckId: map['deck_id'],
      question: map['question'],
      answer: map['answer'],
    );
  }

  // Convert flashcard object to map for DB
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'deck_id': deckId,
      'question': question,
      'answer': answer,
    };
  }
}
